[build]
# 빌드 명령어 - 빌드 스크립트 사용
command = "./build.sh"

# 빌드 결과물 디렉토리
publish = "site"

# 환경 변수
[build.environment]
PYTHON_VERSION = "3.11"

# 리다이렉트 설정
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# 헤더 설정 (보안 및 성능)
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://polyfill.io; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self';"

# 정적 파일 캐싱
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# 폰트 파일 캐싱
[[headers]]
for = "/*.woff2"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# HTML 파일 캐싱 (짧은 시간)
[[headers]]
for = "/*.html"
[headers.values]
Cache-Control = "public, max-age=3600"
